export const SCENE_KEYS = Object.freeze({
  BATTLE_SCENE: 'BATTLE_SCENE',
  BOOT_SCENE: 'BOOT_SCENE',
  GAME_SCENE: 'GAME_SCENE',
  GAME_OVER_SCENE: 'GAME_OVER_SCENE',
  MAIN_MENU_SCENE: 'MAIN_MENU_SCENE',
  PRELOADER_SCENE: 'PRELOADER_SCENE',
  TITLE_SCENE: 'TITLE_SCENE',
  WORLD_SCENE: 'WORLD_SCENE'
})
