export const BATTLE_BACKGROUND_ASSET_KEYS = Object.freeze({
  FOREST: 'FOREST',
  FOREST_BASE: 'FOREST_BASE',
  FOREST_BASE_FOE: 'FOREST_BASE_FOE'
})

export const PKM_NAME_KEYS = Object.freeze({
  HERACROSS: 'Heracross',
  CHANDELURE: 'Charmander'
})

export const GENERAL_ASSET_KEYS = Object.freeze({
  PAUSE_ARROW: 'PAUSE_ARROW'
})

export const DATABOX_ASSET_KEYS = Object.freeze({
  DATABOX_NORMAL: 'DATABOX_NORMAL',
  DATABOX_NORMAL_FOE: 'DATABOX_NORMAL_FOE',
  OVERLAY_HP: 'OVERLAY_HP',
  OVERLAY_EXP: 'OVERLAY_EXP'
})

export const POKEMON_FRONT_ASSET_KEYS = Object.freeze({
  HERACROSS: 'HERACROSS'
})

export const POKEMON_BACK_ASSET_KEYS = Object.freeze({
  CHANDELURE: 'CHANDELURE'
})

export const POKEMON_SHADOW_ASSET_KEYS = Object.freeze({
  SHADOW_SMALL: 'SHADOW_SMALL',
  SHADOW_MEDIUM: 'SHADOW_MEDIUM',
  SHADOW_LARGE: 'SHADOW_LARGE'
})

export const DATA_ASSET_KEYS = Object.freeze({
  ANIMATIONS: 'ANIMATIONS',
  MOVES: 'MOVES'
})

export const MOVE_ASSET_KEYS = Object.freeze({
  ICE_SHARD_START: 'ICE_SHARD_START',
  ICE_SHARD: 'ICE_SHARD',
  SCRATCH: 'SCRATCH'
})

export const TILE_ASSET_KEYS = Object.freeze({
  RED_TILE: 'RED_TILE'
})

export const WORLD_ASSET_KEYS = Object.freeze({
  WORLD_BACKGROUND: 'WORLD_BACKGROUND',
  WORLD_MAIN_LEVEL: 'WORLD_MAIN_LEVEL',
  WORLD_FOREGROUND: 'WORLD_FOREGROUND'
})

export const CHARACTER_ASSET_KEYS = Object.freeze({
  PLAYER: 'PLAYER',
  NPC: 'NPC'
})
